config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

PushkinContest::Application.routes.draw do

  root 'rating#index'

  resources :users, path: '/registration', only: [:create] do
    collection do
      get '/', to: 'users#new'
    end
  end

  resources :rating, only: [:index]
  resources :documentation, only: [:index]

  post 'quiz', to: 'quiz#answer'
  post 'debug/reset', to: 'debug#reset'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/poem.rb
class Poem < ActiveRecord::Base
  scope :random_poem, -> { order('random()').limit(1).first }





end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :set_token, on: :create
  before_save :set_level

  validates :username, :token, uniqueness: true
  validates :url, :username, :name, :surname, :skype, :github, :phone, :vk, presence: true
  validates :url, format: { with: URI::regexp, message: 'Not valid URL' }
  validates :url, format: { with: /\A.*\.herokuapp\.com\z/,
                            message: 'Invalid url. Only herokuapp domains are allowed. Example domain:  http://pushckinrocks.herokuapp.com' }

  validates_with ConfirmRegistrationValidator, on: :create

  has_paper_trail

  scope :not_winners, -> { where(winner: false) }
  scope :rating, -> { order('rating desc') }

  def set_token
    self.token = SecureRandom.hex
  end

  def win?
    self.rating >= 800
  end

  def set_level
    # [0..99] => 1 etc
    self.level = [(self.rating || 0) / 100 + 1, 9].min
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/debug_controller.rb
class DebugController < ApplicationController
  
  def reset
    @token = params[:token]
    @level = params[:level] ? params[:level].to_i : 1
    
    @user = User.find_by_token(@token)
    message = ''
    if !@user
      message = "User with this token doesn't exist"
    elsif !@level.between? 1, 8
      message = "Level should be in range [1..8]"
    else
      @user.update_attributes(rating: (@level - 1) * 100)
      message = "Level successfully updated" 
    end
    render json: { message: message }
  end
end

app/controllers/documentation_controller.rb
class DocumentationController < ApplicationController
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  helper_method :quiz_answer_request
  respond_to :json

  skip_before_filter :verify_authenticity_token, :only => [:answer]

  def answer
    if quiz_answer_request.invalid?
      render json: { errors: quiz_answer_request.errors.full_messages }, status: :error
      return
    end

    message = ''

    @answer = params[:answer]
    @task = Task.find params[:task_id]
    if convert(@task.answer) == convert(@answer)
      ActiveRecord::Base.transaction do
        t = Task.find_by(answered: false, id: params[:task_id])
        if t
          t.update_attributes(answered: true, user_id: user.id)
          user.increment! :rating, 1
          user.update_attributes(winner: true, win_at: Time.zone.now) if user.win?
          message = 'Correct'
        else
          message = 'Task is expired'
        end
      end
    else
      message = 'Wrong'
    end

    render json: { message: message }, status: :ok
  end

  def user
    @user||= quiz_answer_request.user
  end

  def task
    @task ||= quiz_answer_request.task
  end

  def quiz_answer_request
    @quiz_answer_request ||= QuizAnswerRequest.new(request_params)
  end

  def request_params
    params.slice(:token, :task_id, :answer)
  end

  def convert(string)
    string.mb_chars.downcase.normalize.squish.gsub(/\p{P}/, '').to_s
  end

end

app/controllers/rating_controller.rb
class RatingController < ApplicationController

  NUM_USERS = 15.freeze

  def index
    @users = User.rating.limit(NUM_USERS)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'Success'
    else
      render :new
    end

  end

  private

  def user_params
    params.require(:user).permit(:username, :url, :name, :surname, :skype, :github, :phone, :vk)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documentation/index.html.erb
<div class='container'>
  <h2>Описание протокола pushkin-contest</h2>

  <p>Суть соревнования - первым успеть дать ответ на задание, связанное сo стихами А. С. Пушкина =)<br>
    В соревновании учавствуют только сервера, размещенные на heroku.</p>

  <h3>Регистрация</h3>
  <p>При регистрации на сайте pushkin-contest.ror.by пользователь должен указать свое имя (<b>USERNAME</b>) и адрес своего приложения (<b>APP_URL</b>). Принимаются только приложения, имеющие адреса вида '<b>http://myapp.herokuapp.com</b>'</p>
  <p>В процессе регистрации высылается token пользователя на адрес 'APP_URL<b>/registration</b>'. Запрос имеет тип <b>POST</b></p>

  <div class="well">
    <p>params[:question] - тестовый вопрос<br>
    <p>params[:token] - токен пользователя (<b>USER_TOKEN</b>), который необходимо сохранить и использовать в дальнейшем при отправке заданий.</p>
  </div>
  <p>Токен представляет собой строку вида '7baced8d61aa5d47e0a7059c1ceaa4ba'</p>
  <p><b>Пример тестового задания</b></p>
  <p><b>Вопрос</b>:  'Буря %WORD% небо кроет, Вихри снежные крутя'<br>
  <b>Ответ пользователя</b>: {answer: 'мглою'}</p>

  <p>Отправить ответ можно следующим образом:</p>

  <div class="well">
    <p>render json: {answer: 'мглою'}</p>
  </div>


  <p>Для того, чтобы сбросить свою статистику до определенного уровня (от 1 до 8), необходимо отправить <b>POST</b> запрос в следующем формате:<p> 
  <div class="well">
    <p>http://pushkin.rubyroid.by/debug/reset?token=<b>USER_TOKEN</b>&level=<b>DESIRED_LEVEL</b></p>
  </div>

  <h3>Задания</h3>

  <p>После регистрации сервер будет отправлять задания по адресу APP_URL<b>/quiz</b>. Запросы имеют тип POST. Ответ пользователя должен быть пустым со статусом 2XX. Пример: render nothing: true. Ответ на задание посылается отдельным HTTP запросом.</p>

  <p>Пример вопроса:</p>
  <div class="well">
    <p><b>Вопрос</b>:</p>
    <pre>
{
  "question" => "Отчизны внемлем призыванье",
  "id"       => 6595, # <b>TASK_ID</b>
  "level"    => 1,
}
    </pre>
    <p><b>Ответ</b>:</p>
    <pre>
{
  "answer"  => "К Чeдаеву",
  "token"   => <b>USER_TOKEN</b>,
  "task_id" => <b>TASK_ID</b>
}
    </pre>
  </div>

  <p>Ответ пользователя должен быть послан следующим образом:</p>

  <div class="well">
    <pre>
uri = URI("http://pushkin-contest.ror.by/quiz")
parameters = {
  answer: <b>'ваш ответ'</b>,
  token: <b>'USER_TOKEN (см. процесс регистрации)'</b>,
  task_id:  <b>'id задачи (передано ранее)'</b>
}
Net::HTTP.post_form(uri, parameters)
    </pre>
  </div>

  <p>Сервер проверяет правильность выполнения задания и начисляет пользователю <b>1 балл рейтинга</b>, если он ответил первым. Затем генерируется новое задание соответствующего уровня и посылается всем пользователям этого уровня.<br>

  <p>Пользователи также имеют систему уровней, уровень определяется рейтингом пользователя. Пользователю отсылаются задания только его уровня сложности.</p>

  <h3>Уровни сложности</h3>
  <p>Задания, генерируемые сервером, имеют 8 уровней сложности:</p>

  <ol>
    <li><b>Вопрос</b>: одна строчка из любого стихотворения. <br><b>Ответ</b>: название стихотворения</li><br>
    <li><b>Вопрос</b>: одна строчка из любого стихотворения c одним замененным словом (слово заменяется на <b>%WORD%</b>) <br><b>Ответ</b>: замененное слово</li><br>
    <li><b>Вопрос</b>: две строчки подряд из одного произведения замененным словом в каждой (слово заменяется на <b>%WORD%</b>, строчки отделяются друг от друга с помощью <b>\n</b>) <br><b>Ответ</b>: два замененных слова в порядке следования строк через запятую</li><br>
    <li><b>Вопрос</b>: три строчки подряд из одного произведенияиз c одним замененным словом в каждой (слово заменяется на <b>%WORD%</b>, строчки отделяются друг от друга с помощью <b>\n</b>) <br><b>Ответ</b>: три замененных слова в порядке следования строк через запятую</li><br>
    <li><b>Вопрос</b>: одна строчка из любого стихотворения c одним замененным словом (слово заменяется на любое слово, выбранное из стихотворений Пушкина) <b><br>Ответ</b>:   правильное слово и его замененный варинт через запятую</li><br>
    <li><b>Вопрос</b>: одна строчка из любого стихотворения, без знаков препинания, в которых переставлены местами буквы в рамках каждого слова <b><br>Ответ</b>: правильная строка</li><br>
    <li><b>Вопрос</b>: одна строчка из любого стихотворения, без знаков препинания, в которых переставлены местами буквы в рамках всей строчки<b><br>Ответ</b>: правильная строка</li><br>
    <li><b>Вопрос</b>: одна строчка из любого стихотворения, без знаков препинания, в которых переставлены местами буквы в рамках всей строчки и 1 буква заменена<b><br>Ответ</b>: правильная строка</li><br>
  </ol>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PushkinContest</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rating/index.html.erb
<meta http-equiv="refresh" content="5">
<div class="row">
  <div class="container">
    <hr>

    <div class="jumbotron">
      <div class="container">
        <div class='col-md-9'>
          <h1><b><i>Pushkin Сontest</i></b></h1>

          <h3>Rails application for the Rubyroid task.  <%= link_to('About', documentation_index_path) %></h3>

          <p><%= link_to('Sign up', users_path, class: 'btn btn-primary btn-lg') %></p>

        </div>
        <div class='col-md-3'>
          <img src="/images/pushkin.gif" height="100%" width="100%"/>
        </div>
      </div>
    </div>

    <hr>

    <div class='col-md-12'>
      <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">Рейтинг</div>

        <!-- Table -->
        <table class="table">
          <thead>
          <tr>
            <th>№</th>
            <th>Username</th>
            <th>Score</th>
            <% if @users.any?(&:winner?) %>
              <th>Completed</th>
            <% end %>
          </tr>
          </thead>
          <tbody>
          <% @users.each_with_index do |u, index| %>
              <% color = u.winner? ? 'red' : 'white'%>
              <tr style='background-color: <%= color %>;'>
                <th><%= index + 1 %></th>
                <th><%= u.username %></th>
                <th><%= u.rating %></th>
                <% if @users.any?(&:winner?) %>
                  <td><%= u.win_at %></td>
                <% end %>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/_errors.html.erb
<% unless @user.errors.empty? %>
    <div id = 'errors' class="alert alert-danger">
      <a class="close" data-dismiss="alert" href="#">&times;</a>

      <div>Registration failed</div>
      <ul>
        <% @user.errors.full_messages.each do |e| %>
            <li><%= e %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<div class="panel panel-default" style="width: 30%; margin: 50px auto">
  <div class="panel-body">

    <h2>Registration</h2>

    <%= simple_form_for(@user, url: users_path) do |f| %>

        <%= render partial: 'errors' %>

        <div class="form-inputs">
          <%= f.input :username, :required => true, :autofocus => true %>
          <%= f.input :name, :required => true %>
          <%= f.input :surname, :required => true %>
          <%= f.input :skype, :required => true %>
          <%= f.input :github, :required => true %>
          <%= f.input :phone, :required => true %>
          <%= f.input :vk, :required => true %>
          <%= f.input :url, :required => true %>
        </div>


        <div class="form-actions">
          <%= f.button :submit, 'Sign up', class: 'btn btn-primary btn-lg'%>
        </div>
        <hr>
        <p><%= link_to('Terms of registration', documentation_index_path) %></p>

    <% end %>

  </div>
</div>

<script>
  $(function(){
      $(".button").click(function(){
          $('#errors').hide();
      })
  })
</script>